(define (square-tree tree)
    (tree-map square tree)    
)
(define (square number)
    (* number number)
)
(define (tree-map fnc tree)
     (map 
        (lambda (sub-tree) 
            (if (pair? sub-tree)
                (square-tree2 sub-tree)    
                (fnc sub-tree)
            )
        ) 
    tree)
)
(define tree-demo (list 1 (list 2 (list 3 4) 5) (list 6 7)))
(define (main)
    (display (square-tree tree-demo))    
)