(define (cons x y)
    (lambda (m) (m x y))
)
(define (car z)
 (z (lambda (p q) p))
)
(define (cdr z)
 (z (lambda (p q) q))
)

(define (main)
    (display (car (cons 5 13)))
    (newline)
    (display (cdr (cons 5 13)))
)
;car 
; (car (cons x y))
; (car (lambda (m) (m x y)))
; ((lambda (m) (m x y)) (lambda (p q) p))
; ((lambda (m) (m x y)) (lambda (x y) y))
; ((lambda (x y) y) x y)
; (y)