(load "2.48.scm")
; a)
(segments->painter '((make-segment tl tr) 
    (make-segment tr br)
    (make-segment br bl)
    (make-segment bl tl)
    ))
; b)
(segments->painter '((make-segment tl br) 
    (make-segment tr bl)
    ))
; c)
(segments->painter '((make-segment top right) 
    (make-segment right bottom)
    (make-segment bottom left)
    (make-segment left top)
    ))
; d)
