(load "2.56.scm")
(define (addend exp)
    (cadr exp)
)
(define (augend exp)
    (if (null? (cdddr exp))
        (caddr exp)
        (cons (car exp) (cddr exp))
    )
)
(define (multiplier exp)
    (cadr exp)
)
(define (multiplicand exp)
    (if (null? (cdddr exp))
        (caddr exp)
        (cons (car exp) (cddr exp))
    )
)

(define (main)
    (deriv '(* x y (+ x 3)) 'x)
)