(define a 3)
(define b (+ a 1))
(define main (and  
   (eqv? (+ 5 3 4) 12 )
   (eqv? (- 9 1) 8 )
   (eqv? (/ 6 2) 3 )
   (eqv? (+ (* 2 4) (- 4 6) ) 6)
   (eqv? (+ a b (* a b)) 19)
   (eqv? (= a b) #f)
   (eqv? (if (and (> b a) (< b (* a b)))
      b
      a) 4)
   (eqv? (cond ((= a 4) 6)
         ((= b 4) (+ 6 7 a))
         (else 25)) 16)
   (eqv? (+ 2 (if (> b a) b a)) 6)
   (eqv? (* (cond ((> a b) a)
            ((< a b) b)
            (else -1))
      (+ a 1)) 16)
))