(define (sum term a next b)
    (define (iter a result)
        (if (> a b)
            result
            (iter (next a) 
                (+ (term a)
                (sum term (next a) next b)
                )
            )
        )
    )
    (iter a 0)
)