(load "../tools/average.scm")
(load "../tools/reduce.scm")
(load "./1.43.scm")
(define dx 0.0001)
(define (smooth fn)
  (lambda (x) 
    (average (fn (- x dx))
        (fn x)
        (fn (+ x dx))
    )
  )
)
(define (smooth-repeated fn count)
    ((repeated smooth  count) fn)
)

(define (main)
    ((smooth-repeated square 2) 5)
)
